kind: PersistentVolume
apiVersion: v1
metadata:
  name: student-pv 
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /vol/studentDB
    server: 192.168.1.181
