apiVersion: "v1"
kind: Service
metadata:
  name: nfs-nginx
  labels:
    app: web
spec:
  selector:
    app: web
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 8089
     nodePort: 30002
     protocol: TCP
